"""added user relation to tasks

Revision ID: e8c24ae804ba
Revises: 2bd1ef51b605
Create Date: 2025-09-27 16:21:15.726262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8c24ae804ba'
down_revision: Union[str, Sequence[str], None] = '2bd1ef51b605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_user_tasks', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_tasks', type_='foreignkey')

    # ### end Alembic commands ###
